test(phpunit): allow php 7.2 and 7.3 to fail
TODO we need to fix those (in php 7.3) at some point:

There were 2 errors:

1) Sabre\VObject\FreeBusyGeneratorTest::testGenerator with data set #0
('BEGIN:VCALENDAR\nBEGIN:VEVENT\n...LENDAR', '20110101T120000Z/20110101T130000Z')
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
/home/travis/build/tine20/vobject/lib/FreeBusyGenerator.php:215
/home/travis/build/tine20/vobject/tests/VObject/FreeBusyGeneratorTest.php:338

2) Sabre\VObject\TimezoneUtilTest::testTimeZoneBCIdentifiers with data set #52 ('Canada/East-Saskatchewan')
Exception: DateTimeZone::__construct(): Unknown or bad timezone (Canada/East-Saskatchewan)
/home/travis/build/tine20/vobject/tests/VObject/TimeZoneUtilTest.php:181